feat: Add DayOfWeek to printer columns in CRD

diff --git a/.github/workflows/pipeline-build.yml b/.github/workflows/pipeline-build.yml
--- a/.github/workflows/pipeline-build.yml
+++ b/.github/workflows/pipeline-build.yml
@@ -77,6 +77,7 @@ jobs:
           git clone --branch gh-pages https://github.com/${{ github.repository_owner }}/drowzee.git existing-charts || true
           mkdir -p packaged-charts
 
+          # If main branch, we need to remove all dev versions
           if [[ "${GITHUB_REF##*/}" == "main" ]]; then
             for file in existing-charts/*; do
               if [[ ! $(basename "$file") == drowzee-${{ needs.generate-version.outputs.chart-version }}-* ]]; then
@@ -85,6 +86,12 @@ jobs:
             done
           else
             cp -n existing-charts/*.tgz packaged-charts/ || true
+          fi
+
+          # Validate that release version is not exist
+          if [[ -e "existing-charts/drowzee-${{ needs.generate-version.outputs.chart-version }}.tgz" ]]; then
+            echo "Error: Release version ${needs.generate-version.outputs.chart-version} already exists"
+            exit 1
           fi
       - name: Set up Helm
         uses: azure/setup-helm@v4
